### ISSUE TITLE
assertIsa for NATs?

### ISSUE THREAD

**Issue by summerstay** [cycorp/issues#13]
I would like to make an assertion about several terms in Cyc. Some are atomic terms and some are non-atomic terms. When I use assertIsa for atomic terms, it works fine:

assertTool.assertIsa('Snoopy','GoodTerm');

but when I make such an assertion about a NAT, it doesn't work:

assertTool.assertIsa('(HighAmountFn PopularityLevel)','GoodTerm');
Java exception occurred:
com.cyc.base.CycApiException: Expected constant not found (HighAmountFn PopularityLevel)

However, when I do this in the browser interface using the Assert window, it works just fine. Perhaps there's a way to use assertSentence to do what I want?

**Comment by witbrock** [comment]
You probably need to construct an object for the functional term.

**Comment by summerstay** [comment]
I guess you mean instead of just using a string in assertIsa, I should create a CycConstantImpl for (HighAmountFn PopularityLevel) and pass that in. I will give it a try. Thanks.
